---
abstract: 'Package that imports Twitter feeds'
author:
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Twitter
provides:
  Catmandu::Importer::Twitter:
    file: lib/Catmandu/Importer/Twitter.pm
    version: 0.02
requires:
  Catmandu: 0.09
  Date::Parse: 2.30
  Moo: 0.009011
  Net::Twitter: 4.00003
  URI::Escape: 3.31
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
